[CACHE_L1]              
; cache access time in nanoseconds
access_time = 1       
; no. of words in cache
capacity = 8          
; no. of words in a line
block_size = 1        
; lines per set
associativity = 1     
; 0->write-through 1-> write-back
write_hit_policy = 1  
; 0->write-allocate 1-> write-around
write_miss_policy = 0 
; 0->True-LRU 1->Pseudo-LRU
eviction_policy = 1   
; enter full path of trace file
trace_file_path = direct_mapped.txt 
; no. of bits required to find a byte in a word
byte_offset = 2

[DRAM]
; main memory access time in nanoseconds
access_time = 90
; no. of bits required to address memory bytes
address_size = 32
; size of data bus
word_size = 32

