[CORE]
total_cores = 2
coherence_protocol = MOESI
cache_2_cache_time = 40

[CACHE_L1]              
; all sizes/associativity should be a power of 2
; cache hit time in nanoseconds
hit_time = 2
; cache miss time in nanoseconds
miss_time = 20
; cache capacity in bytes
capacity = 32768          
; block size in bytes
block_size = 64        
; blocks per set
associativity = 4
; write policy : write_back/ write_through
write_policy = write_back
; write allocate : yes/ no
write_allocate = no
; replacement policy : LRU/ PLRU/ FIFO/ Random
eviction_policy = LRU   
; no. of bits required to find a byte in a word
byte_offset = 2

[DRAM]
; main memory access time in nanoseconds
access_time = 90
; no. of bits required to address memory bytes
address_size = 32
; size of data bus
word_size = 32

